[package]
name = "orders-service"
version = "0.1.0"
edition = "2021"

[dependencies]
async-nats = "0.35.1"
bytes = "1.7.1"
futures = "0.3.30"
serde = "1.0.209"
serde_json = "1.0.127"
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
